kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-std
provisioner: kubernetes.io/azure-disk
parameters:
  skuname: Standard_LRS
  kind: managed
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
